### ISSUE TITLE
System- und Nutzerbot adden

### ISSUE THREAD

**Issue by NullDev** [pr0-dev/Discord-Bot#1]
Siehe https://pr0gramm.com/faq:user-status 

Beispiele: 

- nutzerbot: https://pr0gramm.com/user/Shad0wBot -> ID 13
- systembot: https://pr0gramm.com/user/pr0gramm -> ID 14

Ref: https://github.com/pr0-dev/Discord-Bot/blob/master/src/api/embedHandler.js#L202-L214

**Comment by Scarwolf** [comment]
https://github.com/pr0-dev/Discord-Bot/pull/2
