### ISSUE TITLE
URL-Matching verbessen 💯 

### ISSUE THREAD

**Issue by twobiers** [pr0-dev/Discord-Bot#13]
## Funktions Wunsch

**Funktionen:** <br>
Macht mal, dass der Bot auch triggert, wenn man um den Link ne Nachricht schreibt, nicht nur wenn der Link als einzelne Nachricht eintrudeln tut!!11!!!1

**Comment by NullDev** [comment]
Weiß nicht ob das zu spammy wird. Ggf mach ich ne Per-Guild/Per-Channel option dafür
