### ISSUE TITLE
Automatisches löschen von Posts

### ISSUE THREAD

**Issue by Michl7** [pr0-dev/Discord-Bot#3]
## Funktions Wunsch

**Funktionen:** <br>
Wäre es möglich, dass der Bot nach dem Posten des Bildes/Videos (mit den Stats darunter) den Userpost (mit dem Link) löscht?
Dies würde etwas mehr Ordnung schaffen.

**Comment by NullDev** [comment]
Moin! 

Ja, ist möglich allerdings hab ich mich bewusst dagegen entschieden. Das wurde am disc0rd auch ne Zeit lang so gemacht weil ein paar User das wollten. Nur kurz danach kamen die Beschwerden und auch Verwirrung wieso der Bot denn zufällig von selbst Nachrichten sendet ^^

War dann störender als es hilfreich war und wir haben es wieder raus genommen.

Ich werde das allerdings als konfigurierbare Option in den Bot einbauen. Nur meine Live-Version des Bots wird diese Option dann nicht aktiviert haben. Dann müsste der Bot selbst gehostet werden. Für Server spezifische Optionen fehlt mir leider die Zeit.

**Comment by NullDev** [comment]
Feature hinzugefügt in https://github.com/pr0-dev/Discord-Bot/commit/d58df89c828506f01e3d26ec43526db330b2f01f
