### ISSUE TITLE
http://www.pr0gramm.com/user/{Username}/uploads/{PostId} Funktioniert nicht

### ISSUE THREAD

**Issue by twobiers** [pr0-dev/Discord-Bot#7]
## Fehler Report

**Fehler beschreibung:** <bR>
Links mit user-Referenz funktionieren nicht.

**Reproduzierung:** <bR>
Wie kann man den Fehler reproduzieren?

1. Schreibe Link ('http://www.pr0gramm.com/user/{Username}/uploads/{PostId}') in discord

**Erwartetes Resultat:** <bR>
Der Bot sollte mit dem eingebetteten Bild antworten und Informationen dazu anzeigen. Es wird jedoch als normaler Link erkannt

**Screenshots:** <bR>
https://i.imgur.com/I3Mghs2.png

**Umgebung:** <bR>
disc0rd-Server

**Comment by NullDev** [comment]
Danke für den Issue!

Dieses Problem betrifft allerdings nur den Bot auf dem offiziellen pr0gramm Discord (disc0rd) Server. Der Bot, der auf GitHub gehostet wird, läuft unabhängig. User Verlinkung funktionieren in dieser Version.

Der Fehler im anderen Bot ist bekannt und wird mit Version zwei des disc0rd bot's (nicht auf GitHub) behoben.
